style.fill: transparent
grid-columns: 2

a:"" {
    style.fill: transparent
    style.stroke: transparent
    direction: right
    farms {
        shape: sql_table
        Name: string {constraint: primary_key}
        City: city {constraint: foreing_key}
        Country: country Rollup
        Webpage: link
    }
}

b:"" {
    style.fill: transparent
    style.stroke: transparent
    direction: right
    countries: {
        shape: sql_table
        Name: string {constraint: primary_key}
        Continent: continent {constraint: foreign_key}
    }
    
    cities: {
        shape: sql_table
        Name: string {constraint: primary_key}
        Region: region {constraint: foreing_key}
        Country: country Rollup
        Continent: continent Rollup
    }
}

a.farms.City -> b.cities.Name
a.farms.Country -> b.countries.Name: Rollup {
    style {
        stroke-dash: 3
    }
}