style.fill: transparent
grid-columns: 3
grid-rows: 2

a:"" {
    style.fill: transparent
    style.stroke: transparent
    direction: right
    recolte: Récolte
    sechage: Séchage
    fermentation: Fermentation complémentaire
    fermentation.style.font-size: 8
    fermentation.style.stroke-dash: 3
    exportation
}


b: "" {
    style.fill: transparent
    style.stroke: transparent
    direction: left
    torrefaction: Torréfaction
    preparation: Préparation
}

a.recolte -> a.sechage
a.sechage -> a.fermentation {
    style {
        stroke-dash: 3
    }
}
a.fermentation -> a.exportation {
    style {
        stroke-dash: 3
    }
}
a.sechage -> a.exportation
a.exportation -> b.torrefaction
b.torrefaction -> b.preparation: vente
